# This is a basic workflow to help you get started with Actions

name: Deploy web app on Github Pages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/setup-node@v1.4.2
        with:
          node-version: 13.12
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build
        run: |
          yarn install --forzen-lockfile
          yarn build --production

      # Runs a set of commands using the runners shell
      - name: Push to gh-pages branch
        run: |
          cd build
          git init
          git config --global user.email sarusethi@rocketmail.com
          git config --global user.name Gurleen Sethi
          git remote add origin https://${{secrets.PERSONAL_ACCESS_TOKEN}}@github.com/$GITHUB_REPOSITORY.git
          git checkout -b gh-pages
          git add .
          git commit -m "Deployment of web app."
          git push origin gh-pages -f
